language: java
sudo: false
jdk:
  - oraclejdk11
before_script:
  - git clone --depth=1 https://github.com/oracle/graal.git -b release/graal-vm/19.3 /tmp/graal  
script:
  - ant test -Dgraal.dir="/tmp/graal"
  - ant checkstyle -Dgraal.dir="/tmp/graal"
